### ISSUE TITLE
Training with more laser scans

### ISSUE THREAD

**Issue by FrancescoTerrosi** [ROBOTIS-GIT/turtlebot3_machine_learning#31]
Hello there,
I forked this repo because I need an already-implemented neural network to implement some safety checks on it, but this is another story.
Since my main focus is safety, I need the robot to get 'realistic' scan data and for that reason I expanded the state_space from 26 to 362 as pointed in #2 
I am training the robot in a different environment from the ones provided by the example (i.e. turtlebot_house_world) and I noticed that, when using more laser data, the robot just keep cycling like it is about to explode, while if I don't modify the state_space (as is the default implementation) I get decent performances.

My question is: is there something in the code I need to modify in order to adapt the robot to work with more sensor data or probably it's just a matter of more training?

Thank you very much,
Cheers

**Comment by ROBOTIS-Will** [comment]
@FrancescoTerrosi 
Hi,
When you increase the resolution of the scan data, this could cause trouble in learning due to the expanded state_size.
In order to resolve this issue, you can increase the scan data resolution little by little to find a proper resolution that works, or perform hyper parameter tuning by adjusting learning_rate, step, batch size and so on.
Thank you.
