### ISSUE TITLE
Goal is not being achieved for Distant Goal

### ISSUE THREAD

**Issue by RiyaPahwa** [ROBOTIS-GIT/turtlebot3_machine_learning#36]
For nearby goals, turtlebot3 reaches the goal position, but for distant goals, it is not able to reach the goal position.

**Comment by ROBOTIS-Will** [comment]
@RiyaPahwa 
Could you be more specific on "not able to reach the goal position for a distant goal"?
It will be much helpful to see the actual issue or any error message on the screen.

**Comment by RiyaPahwa** [comment]
There is no error message on screen, but when the goal is far from the turtlebot's position, it does not reach the goal and keeps moving around certain point.

**Comment by RiyaPahwa** [comment]
Also, if I keep the goal fixed at some corner of the maze, the turtlebot never reaches the goal and just keeps moving.

**Comment by ROBOTIS-Will** [comment]
@RiyaPahwa 
If the navigation is not successful under a specific map, you might want to adjust some navigation parameter so that the robot can navigate in the custom map.
Please see below eManual for tuning navigation parameters.
http://emanual.robotis.com/docs/en/platform/turtlebot3/navigation/#tuning-guide

**Comment by ROBOTIS-Will** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if necessary. Thanks.
